name: monitor_it
description: A Flutter app for activity monitoring and analysis
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  http: ^1.2.0
  video_player: ^2.8.2
  file_picker: ^6.1.1
  dio: ^5.4.0
  permission_handler: ^11.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true